baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = "StrMnL's Blog"
theme = 'JuiceBar'

[params]
author = "StrMnL"
description = "My site description"
authorImage = "/images/profile.png"
paginate = 5 
Title = "Starry Minnelli's Blog"
content = "(*^▽^*) 你好！"
imageUrl = "/images/profile.png"

# 添加新的社交图标
# 更多社交图标可以在JuiceBar\layouts\partials\svg.html中找到
[[params.social]]
name = "bilibili"
url = "https://space.bilibili.com/358196405"

[[params.social]]
name = "Github"
url = "https://github.com/StrMnL"

# [[params.social]]
# name = "telegram"
# url = "https://t.me/Hotjuice"

# [[params.social]]
# name = "twitter"
# url = "https://twitter.com/hotjuicee"

[[params.social]]
name = "email"
url = "sitarui78@gmail.com"

# [[params.social]]
# name = "instagram"
# url = "your_url"

# [[params.social]]
# name = "mastodon"
# url = "your_url"

# [[params.social]]
# name = "reddit"
# url = "your_url"

# [[params.social]]
# name = "stackoverflow"
# url = "your_url"

[taxonomies]
category = "categories"
tag = "tags"

# 添加新的导航链接
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

# 如果使用giscus评论系统
#[params.giscus]
#repo = "ENTER REPO HERE"
#repoID = "ENTER REPO ID HERE"
#category = "ENTER CATEGORY NAME HERE"
#categoryID = "ENTER CATEGORY ID HERE"
#mapping = "og:title"
#reactionsEnabled = "1"
#emitMetadata = "0"
#inputPosition = "bottom"
#lang = "en"
#loading = "lazy"

#用于输出文档的设置（必须的）
[outputs]
home = ["HTML", "RSS", "JSON"]